name: target_sistemas_prova_flutter
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0-139.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.6.4
  http: ^1.1.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.14
  mobx: ^2.2.3+1
  flutter_mobx: ^2.2.0+1

dev_dependencies:
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
